-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [curve25519_dalek]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Curve25519Dalek.Types
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
open curve25519_dalek

/- [subtle::{core::convert::From<u8> for subtle::Choice}::from]:
   Name pattern: [subtle::{core::convert::From<subtle::Choice, u8>}::from]
   Converts a u8 to a Choice. The input should be 0 or 1. -/
def subtle.FromsubtleChoiceU8.from (input : U8) : Result subtle.Choice :=
  if h : input = 0#u8 then
    Result.ok { val := input, valid := Or.inl h }
  else if h' : input = 1#u8 then
    Result.ok { val := input, valid := Or.inr h' }
  else
    Result.fail .panic

/- [subtle::{subtle::ConditionallySelectable for u64}::conditional_select]:
   Name pattern: [subtle::{subtle::ConditionallySelectable<u64>}::conditional_select]
   Conditional select: returns a if choice=0, b if choice=1 -/
def subtle.ConditionallySelectableU64.conditional_select
  (a : U64) (b : U64) (choice : subtle.Choice) : Result U64 :=
  if choice.val = 1#u8 then
    Result.ok b
  else
    Result.ok a
