-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [curve25519_dalek]: type definitions
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace curve25519_dalek

/- [curve25519_dalek::backend::serial::u64::field::FieldElement51]
   Source: 'curve25519-dalek/src/backend/serial/u64/field.rs', lines 43:0-43:47 -/
@[reducible] def backend.serial.u64.field.FieldElement51 := (Array U64 5#usize)

/- [curve25519_dalek::backend::serial::u64::scalar::Scalar52]
   Source: 'curve25519-dalek/src/backend/serial/u64/scalar.rs', lines 26:0-26:34 -/
@[reducible] def backend.serial.u64.scalar.Scalar52 := (Array U64 5#usize)

end curve25519_dalek
