-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [curve25519_dalek]: type definitions
import Aeneas
import Curve25519Dalek.TypesExternal
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace curve25519_dalek

/- [core::panicking::AssertKind]
   Source: '/rustc/library/core/src/panicking.rs', lines 382:0-382:19
   Name pattern: [core::panicking::AssertKind] -/
inductive core.panicking.AssertKind where
| Eq : core.panicking.AssertKind
| Ne : core.panicking.AssertKind
| Match : core.panicking.AssertKind

/- Trait declaration: [subtle::ConditionallySelectable]
   Source: '/home/oliver/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 393:0-393:39
   Name pattern: [subtle::ConditionallySelectable] -/
structure subtle.ConditionallySelectable (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  conditional_select : Self → Self → subtle.Choice → Result Self

/- [curve25519_dalek::backend::serial::u64::scalar::Scalar52]
   Source: 'curve25519-dalek/src/backend/serial/u64/scalar.rs', lines 26:0-26:34 -/
@[reducible] def backend.serial.u64.scalar.Scalar52 := (Array U64 5#usize)

/- [curve25519_dalek::backend::serial::u64::field::FieldElement51]
   Source: 'curve25519-dalek/src/backend/serial/u64/field.rs', lines 43:0-43:47 -/
@[reducible] def backend.serial.u64.field.FieldElement51 := (Array U64 5#usize)

/- [curve25519_dalek::scalar::Scalar]
   Source: 'curve25519-dalek/src/scalar.rs', lines 195:0-232:1 -/
structure scalar.Scalar where
  bytes : Array U8 32#usize

end curve25519_dalek
