-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [curve25519_dalek]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- [subtle::Choice]
   Name pattern: [subtle::Choice]
   A constant-time boolean represented as 0 or 1 -/
structure subtle.Choice where
  val : U8
  valid : val = 0#u8 ∨ val = 1#u8
